sudo: false
language: node_js
cache:
  directories:
    - node_modules

node_js:
  - '6'
  - '8'

before_install:
  - if [[ `npm -v` != 4* ]]; then npm i -g npm@4.0.2; fi

before_script:
  - npm prune

script:
  - npm run pre-release

after_success:
  - npm run upload-coverage
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

notifications:
  email:
    recipients:
      - u_glow@hotmail.com
